export const changeLanguage = "changeLanguage";

//Success for thunk
export const GET_HOME_SUCCESS = "GET_HOME_SUCCESS"
export const GET_SERVICES_SUCCESS = "GET_SERVICES_SUCCESS"
export const GET_PORTFOLIOS_SUCCESS = "GET_PORTFOLIOS_SUCCESS"
export const GET_ABOUT_SUCCESS = "GET_ABOUT_SUCCESS"
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS"
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS"
export const GET_FEEDBACKS_SUCCESS = "GET_FEEDBACKS_SUCCESS"

//Error for thunk
export const GET_HOME_ERROR = "GET_HOME_ERROR"
export const GET_ABOUT_ERROR = "GET_ABOUT_ERROR"
export const GET_SERVICES_ERROR = "GET_SERVICES_ERROR"
export const GET_PORTFOLIOS_ERROR = "GET_PORTFOLIOS_ERROR"
export const GET_PROJECTS_ERROR = "GET_PROJECTS_ERROR"
export const GET_CONTACTS_ERROR = "GET_CONTACTS_ERROR"
export const GET_FEEDBACKS_ERROR = "GET_FEEDBACKS_ERROR"

//Social media type
export const YOUTUBE = 'YOUTUBE'
export const BEHANCE = 'BEHANCE'
export const LINKEDIN = 'LINKEDIN'
export const DRIBBLE = 'DRIBBLE'
export const FACEBOOK = 'FACEBOOK'
export const INSTAGRAM = 'INSTAGRAM'